### PR TITLE
added-display-captions-option

### PR DESCRIPTION
**Pull request by N-Shar-ma**
Added an option to display instagram post captions as overlay on the posts on hovering.  display_caption is true by default. A screenshot of the caption visible on hovering is attached:

image

### CODE REVIEW

**Comment by jsanahuja** [comment]
Looks great! I made some small changes:

- Changed `display_captions` default value to `false` to avoid changing the current behavior for users that use the CDN.
- Replaced template string for a normal string (scaping line breaks) as this is [not compatible in any version of IE](https://caniuse.com/template-literals).
- Added a condition to avoid adding any caption styles if `display_captions` is disabled.
- Changed `max-width:100%` for `width:100%` to avoid cases like this:

|image| -> |image|
|---|---|---|

Thank you!

**Review by jsanahuja — APPROVED** [review]

**Comment by jsanahuja** [comment]
Closes #14

**Comment by N-Shar-ma** [comment]
This was my first ever pull request. Thank you for letting me contribute, and for explaining the tweaks you made. I learnt a lot from this experience 😊

**Comment by jsanahuja** [comment]
Noo, thank you for your work! Really appreciated

**Pull request merged**
