### PR TITLE
Add optional cache layer to help with (jquery.instagramFeed) issue #25. Default state is not caching. 

### PR DESCRIPTION
**Pull request by cube-dan**
Greets Team InstagramFeed, 

I've added a cache layer to help deal with this error message: 
```log
InstagramFeed: It looks like YOUR network has been temporary banned because of too many requests. See https://github.com/jsanahuja/jquery.instagramFeed/issues/25
```

This adds 3 new config options:
```
   // option.name: default_value
   cache_use: false,
   cache_for: "30:min",
   cache_prefix: "igf_",
```
Docs & version number updated as per CONTRIBUTING.md. 

An aside: I ran into a small snafu with the version number. There's a mismatch between src/
InstagramFeed.js ([@1.4.0](https://github.com/jsanahuja/InstagramFeed/blob/master/src/InstagramFeed.js#L4)) and package.json ([@1.5.4](https://github.com/jsanahuja/InstagramFeed/blob/master/package.json#L5)). I ended up going with 1.6.0 since this is a backwards compatible API change. 

Let me know if you'd like anything changed and **thank you SO much** for an Instagram option that isn’t painful!

-Dan

### CODE REVIEW

**Comment by cube-dan** [comment]
One more thing team InstagramFeed. If you're cool with adding this PR — and after fixing anything you guys want me to — I'll go ahead and add it to [jquery.instagramFeed](https://github.com/jsanahuja/jquery.instagramFeed) also.

**Comment by jsanahuja** [comment]
As it is stated in the [CONTRIBUTING.md](https://github.com/jsanahuja/InstagramFeed/blob/master/CONTRIBUTING.md) file:
> When contributing to this repository, please first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change.

I am sorry but the implementation of the client-side catching should follow what was described in #49

**Review by jsanahuja — CHANGES_REQUESTED** [review]
Should be implemented as it was done in https://github.com/jsanahuja/jquery.instagramFeed/pull/97/files
I don't think we need 3 parameters nor "complex" time specification for this

**Comment by cube-dan** [comment]
I'm not sure what you’re asking for here @jsanahuja. #49 seems to imply that queries should be made through the[ IG graphql url](https://instagram.com/graphql/query/?query_id=17888483320059182&variables={"id":"USERID","first":20,"after":null}) instead of how you guys are doing it now; scraping returned html. 

I'm also confused about what you mean by:
> Should be implemented as it was done in https://github.com/jsanahuja/jquery.instagramFeed/pull/97/files

as the url you referenced show code that isn’t  present in the [current version of InstagramFeed](https://github.com/jsanahuja/InstagramFeed/releases/tag/1.5.4). Should I have started the PR from a different branch?

My thoughts on the "complex" time specification come down to the idea of making the API easy on the end user. I agree that 3 variables could be reduced but I didn’t want to be presumptuous by giving the end user no way of turning the caching off, nor assuming that one caching time would fit all. 

I agree with what you said in #97: 
> [I don't really know, depends on how often does people publish on their Instagram accounts.](https://github.com/jsanahuja/jquery.instagramFeed/pull/97#issuecomment-750923572) 

... the cache time needs to be up to the end user.

I also agree that [the default caching state should be "ON"](https://github.com/jsanahuja/jquery.instagramFeed/pull/97#pullrequestreview-558680353)

What would you recommend as a solution, from an end user perspective, that would allow:

1. Easy to "think about" cache time periods
2. Cache on by default

Perhaps `cache_for: false` would turn off caching?

**Comment by jsanahuja** [comment]
> I'm not sure what you’re asking for here @jsanahuja. #49 seems to imply that queries should be made through the[ IG graphql url](https://instagram.com/graphql/query/?query_id=17888483320059182&variables=%7B%22id%22:%22USERID%22,%22first%22:20,%22after%22:null%7D) instead of how you guys are doing it now; scraping returned html.
> 
> I'm also confused about what you mean by:
> 
> > Should be implemented as it was done in https://github.com/jsanahuja/jquery.instagramFeed/pull/97/files
> 
> as the url you referenced show code that isn’t present in the [current version of InstagramFeed](https://github.com/jsanahuja/InstagramFeed/releases/tag/1.5.4). Should I have started the PR from a different branch?
> 
> My thoughts on the "complex" time specification come down to the idea of making the API easy on the end user. I agree that 3 variables could be reduced but I didn’t want to be presumptuous by giving the end user no way of turning the caching off, nor assuming that one caching time would fit all.
> 
> I agree with what you said in #97:
> 
> > [I don't really know, depends on how often does people publish on their Instagram accounts.](https://github.com/jsanahuja/jquery.instagramFeed/pull/97#issuecomment-750923572)
> 
> ... the cache time needs to be up to the end user.
> 
> I also agree that [the default caching state should be "ON"](https://github.com/jsanahuja/jquery.instagramFeed/pull/97#pullrequestreview-558680353)
> 
> What would you recommend as a solution, from an end user perspective, that would allow:
> 
> 1. Easy to "think about" cache time periods
> 2. Cache on by default
> 
> Perhaps `cache_for: false` would turn off caching?

jquery.instagramFeed is the jQuery version of this repository. We do the same on both repositories so the cache thing should be implemented as it was done there in https://github.com/jsanahuja/jquery.instagramFeed/pull/97/files. You can use different ways but the end user API (and default values) must be the same

Thank you :)

**Comment by jsanahuja** [comment]
I am closing this PR as this feature has been implemented in #54

**Comment by cube-dan** [comment]
Thanks for considering the change @jsanahuja. Glad you guys already had caching in the pipe!

I noticed that you guys rolled out #54 with 2.0.2 and that it's [live on packagist](https://asset-packagist.org/package/npm-asset/instafeed) so, [again](https://github.com/jsanahuja/InstagramFeed/pull/54#issuecomment-783657813), thanks for getting caching implemented with the new cache_time var.

**Comment by jsanahuja** [comment]
> it's [live on packagist](https://asset-packagist.org/package/npm-asset/instafeed)

I don't know who mantains that. We only publish it in the [Github NPM Registry](https://github.com/jsanahuja/InstagramFeed/packages/120475) ([more info here](https://github.com/jsanahuja/InstagramFeed/issues/38#issuecomment-686641525)) and [CDNJS](https://cdnjs.com/libraries/InstagramFeed)

Thank you for your support! :)

**Pull request closed without merging**
